ci/cd:
  - changed-files:
      - any-glob-to-any-file: ".github/**"
# Add 'Documentation' label to any file changes within 'docs' folder
docs:
  - changed-files:
      - any-glob-to-any-file: "doc/**"
      - any-glob-to-any-file: "**/*.md"
  - head-branch: ["^docs"]
# Add 'feature' label to any PR where the head branch name starts with `feature` or has a `feature` section in the name
feature:
  - head-branch: ["^feat"]
fix:
  - head-branch: ["^fix"]
  # Add 'release' label to any PR that is opened against the `main` branch
release:
  - base-branch: "main"
