name: Lint

on:
  pull_request:
    branches: [main,master]
  workflow_call:
  workflow_dispatch:

jobs:

  lint:
    name: lint
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - uses: actions/setup-python@v4

      - name: install dependencies
        run: |
          brew install shellcheck shfmt zsh
          pip install --user linkify-it-py mdformat mdformat-config mdformat-gfm mdformat-shfmt mdformat-tables mdformat-toc

      - name: commit
        uses: wagoid/commitlint-github-action@v5
        with:
          configFile: '.commitlintrc'

      - name: markdown
        run: find . -name '*.md' ! -name 'CHANGELOG.md' -type f -print0 | xargs -0 -n1 -P4 mdformat --check --wrap 120

      - name: shell format
        run: find . -name '*.sh' -type f -print0 | xargs -0 -n1 -P4 shfmt -bn -ci -d -i 2 -ln bash -s -sr

      - name: shell logic
        run: find . -name '*.sh' -type f -print0 | xargs -0 -n1 -P4 shellcheck

      - name: zsh syntax
        run: find . -name '*.zsh' -type f -print0 | xargs -0 -n1 -P4 zsh -n

      - name: zsh compile
        run: find . -name '*.zsh' -type f -exec zsh -fc "zcompile {}" \;
