name: Lint

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: install dependencies
        run: |
          brew install shellcheck shfmt zsh
          pip3 install --user linkify-it-py mdformat mdformat-config mdformat-gfm mdformat-shfmt mdformat-tables mdformat-toc

      - name: markdown lint
        run: find . -name '*.md' ! -name 'CHANGELOG.md' -name '*.md' -type f -print0 | xargs -0 -n1 -P4 mdformat --check --wrap 120

      - name: shell format lint
        run: find . -name '*.sh' -type f -print0 | xargs -0 -n1 -P4 shfmt -bn -ci -d -i 2 -ln bash -s -sr

      - name: shell logic lint
        run: find . -name '*.sh' -type f -print0 | xargs -0 -n1 -P4 shellcheck

      - name: zsh syntax lint
        run: find . -name '*.zsh' -type f -print0 | xargs -0 -n1 -P4 zsh -n

      - name: zsh compile lint
        run: find . -name '*.zsh' -type f -exec zsh -fc "zcompile {}" \;
