name: Sync GitHub Actions workflows

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
  schedule:
    - cron:  '*/10 * * * *' # Run every 10 minutes.

jobs:
  sync-workflows:
    name: Sync GitHub Actions workflows
    runs-on: ubuntu-latest
    steps:
      - name: Sync files
        uses: adrianjost/files-sync-action@v1.5.1
        with:
          COMMIT_MESSAGE: 'ci: update synced github action workflows'
          FILE_PATTERNS: |-
            ^linting.yml$
            ^cleanup-runs.yml$
            ^release.yml$
          SRC_ROOT: /.github/workflows/
          TARGET_ROOT: /.github/workflows/
          TARGET_REPOS: |-
           vladdoster/dotfiles
           vladdoster/neovim-configuration
           vladdoster/hammerspoon-configuration
          GIT_EMAIL: mvdoster@gmail.com
          GIT_USERNAME: vladdoster
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
